apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '>=0.0.3'
  values:
    podinfo:
      ui:
        color: "#34577c"
        message: "Hi, this message is from the Helm values for dev-test"
      image:
        repository: ghcr.io/weavegitops/application-promotion-podinfo # {"$imagepolicy": "app-podinfo:podinfo-latest:name"}
        tag: 2b6e79b6f1c485b89c1f13f45e7972c19b02df18-25 # {"$imagepolicy": "app-podinfo:podinfo-latest:tag"}
