apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '>=0.0.3'
  values:
    podinfo:
      ui:
        color: "#34577c"
        message: "Hi, this message is from the Helm values for dev-test"
      image:
        repository: ghcr.io/weavegitops/application-promotion-podinfo # {"$imagepolicy": "app-podinfo:podinfo-latest:name"}
        tag: c92a9f905b017b43560397d75568f3d0c3ab820b-29 # {"$imagepolicy": "app-podinfo:podinfo-latest:tag"}
