apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '>=1.0.0'
  values:
    podinfo:
      ui:
        color: "#34577c"
        message: "Hi, this message is from the Helm values for dev-test"
      image:
        repository: ghcr.io/weavegitops/application-promotion-podinfo # {"$imagepolicy": "app-podinfo:podinfo-latest:name"}
        tag: 98a128940ca3009dfb433e7e93793cb82fd42696-15 # {"$imagepolicy": "app-podinfo:podinfo-latest:tag"}
