---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: dev-test-promote
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: application-promotion-podinfo
  update:
    path: ./image-automation/dev-test
    strategy: Setters

