apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podinfo-kustomize-sync
  namespace: flux-system
spec:
  providerRef:
    name: github-app-podinfo
  summary: "env=dev"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: app-promo-podinfo-dev
      namespace: flux-system
