---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: app-podinfo
spec:
  image: ghcr.io/weavegitops/application-promotion-podinfo
  interval: 1m0s
  secretRef:
    name: ghcr-pull-image-creds
