apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-dev
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.2.0' # {"$promotion": "default:app-podinfo:dev"}
  targetNamespace: app-podinfo-dev
  values:
    ui:
      message: "Hi, this message is from the Helm values for dev"
      color: ""
    canary:
      enabled: true
      loadtester:
        url: http://flagger-flagger-loadtester.flagger/
      ingress:
        url: 172.16.30.224/dev/podinfo
