apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: app-podinfo-dev
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.2.1' # {"$promotion": "default:app-podinfo:dev"}
  targetNamespace: app-podinfo-dev
  values:
    service:
      enabled: true
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for dev"
      color: ""
    canary:
      enabled: false
      loadtester:
        url: flagger-loadtester.flux-system
      ingress:
        url: demo3-cluster24.weavegitops.com/dev/podinfo
    hpa:
      enabled: true
      maxReplicas: 1
