apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2m0s
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: '1.x.x'
  values:
    podinfo:
      ui:
        color: "#34577c"
        message: "Hi, this message is from the Helm values"
      image:
        repository: ghcr.io/weavegitops/application-promotion-podinfo
        tag: 0.0.1
