name: Check Versions,Build & Push Container, Test Helm and Release Helm Chart

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # important parameter

    - name: Container Version
      id: version
      run: |
        VERSION=$(grep "var VERSION" pkg/version/version.go | sed -e 's/^var VERSION = "//' -e 's/"$//')
        echo "The container tag will be set to ${VERSION} once merged to main"
        echo ::set-output name=VERSION::${VERSION}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
               ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION  }}

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.9.2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.2.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      run: ct lint --target-branch ${{ github.event.repository.default_branch }} --chart-repos podinfo=https://stefanprodan.github.io/podinfo

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      if: steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: |
        cd charts
        ct install --charts podinfo --target-branch ${{ github.event.repository.default_branch }} --chart-repos podinfo=https://stefanprodan.github.io/podinfo
      if: steps.list-changed.outputs.changed == 'true'

    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      with:
        charts_dir: charts
        charts_repo_url: https://raw.githubusercontent.com/application-promotion-podinfo/gh-pages/
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
