name: Docker Image CI

on:
  push:
    branches:
    - main
    - 'cmd/**'
    
  pull_request:
    branches:
    - main
    - 'cmd/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3

#    - name: Policy Check
#      uses: magalixcorp/magalix-action@main
#      with:
#        webhook: https://console.magalix.com/api/v1/kubeguard/37a381c8-8be9-48cd-a78c-eb6942884a0d/f8bfe49a-a384-44e7-ab7f-71aed721e109
#        auto-remediation: false

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: darrylweaver
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Retrieve Short Commit SHA
      run: |
        VERSION=sha-${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        tags: darrylweaver/podinfo:${{ env.VERSION }}
        push: true

#    - name: Update Image Version in the deployment.yaml for uat
#      uses: fjogeleit/yaml-update-action@main
#      with:
#        valueFile: 'kustomize/deployment.yaml'
#        propertyPath: 'spec.template.spec.containers[0].image'
#        value: darrylweaver/podinfo:${{ env.VERSION }}
#        branch: main
#        targetBranch: uat
#        createPR: true
#        message: 'Update Image Version to ${{ env.VERSION }}'
#        masterBranchName: main

#    - name: Update Image Version in the deployment.yaml for prod
#      uses: fjogeleit/yaml-update-action@main
#      with:
#        valueFile: 'kustomize/deployment.yaml'
#        propertyPath: 'spec.template.spec.containers[0].image'
#        value: darrylweaver/podinfo:${{ env.VERSION }}
#        branch: dev
#        targetBranch: main
#        createPR: true
#        message: 'Update Image Version to ${{ env.VERSION }}'
#        masterBranchName: main

