name: Release Helm Chart

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # important parameter

    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      with:
        charts_dir: charts
        charts_repo_url: https://raw.githubusercontent.com/application-promotion-podinfo/gh-pages/
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
